pipeline {
    agent {
        label 'jenkins-slave'
    }
    stages {
        stage('Tag') {
            when {
                branch 'master'
                expression { return build.isRelease() }
            }
            steps {
                revAndTag()
            }
        }
        stage('Test') {
            when {
                branch 'master'
                expression { return build.isRelease() }
            }
            agent {
                docker {
                    image "hutchapp/go-builder:1.11.1"
                    reuseNode true
                }
            }
            steps {
                sh "go test ./..."
            }
        }
        stage('Build') {
            agent {
                docker {
                    image 'hutchapp/go-builder:1.11.1'
                    reuseNode true
                }
            }
            when {
                branch 'master'
                expression { return build.isRelease() }
            }
            steps {
                buildGoCli('esdt', tag.latest())
            }
        }
        stage('Publish') {
            when {
                branch 'master'
                expression { return build.isRelease() }
            }
            steps {
                githubRelease(
                        tag.latest(),
                        tag.latest(),
                        ['esdt/mac/esdt', 'esdt/linux/esdt', 'esdt/win/esdt'],
                        ['mac/esdt', 'linux/esdt', 'win/esdt']
                )
            }
        }
    }
    post {
        failure {
            slackBuildFailure()
        }
    }
}